version: "generic-1.11.3-{build}"

environment:
  matrix:
    - ARCH: x86_64
      CYGWIN: C:\Cygwin64
      CHOST: x86_64-w64-mingw32
      CC: x86_64-w64-mingw32-gcc

build_script:
  - git submodule update --init --recursive
  - "%CYGWIN%\\bin\\bash -lc 'set -eux; cd /cygdrive/c/projects/%APPVEYOR_PROJECT_NAME%; cd lib/spookyhash; git checkout spookyhash-1.0.6; cd -'"
  - "%CYGWIN%\\bin\\bash -lc 'set -eux; cd /cygdrive/c/projects/%APPVEYOR_PROJECT_NAME%; make clean SPI=2.0 SPIVER=v2; make all SPI=2.0 SPIVER=v2'"
  - "%CYGWIN%\\bin\\bash -lc 'set -eux; cd /cygdrive/c/projects/%APPVEYOR_PROJECT_NAME%; make clean SPI=3.0 SPIVER=v3; make all SPI=3.0 SPIVER=v3'"
