language: c
env:
  global:
  - OMP_NUM_THREADS=4
compiler:
- gcc
os:
- linux
- osx
script:
- make clean SPI=2.0 SPIVER=v2 && make all SPI=2.0 SPIVER=v2
- make clean SPI=3.0 SPIVER=v3 && make all SPI=3.0 SPIVER=v3
# - "./lib/travis_build_push.sh"
