language: c
env:
  global:
  - OMP_NUM_THREADS=4
compiler:
- gcc
os:
- linux
- osx
script:
- cd lib/spookyhash/build
- sed -i.bak -e '37,40d' premake5.lua
- "../../travis_build_premake.sh"
- "./premake5 gmake"
- make clean
- ALL_CFLAGS+=-fPIC make
- cd -
- make clean && make SPOOKYPATH=$(dirname `find ./lib/spookyhash/ -name "*libspookyhash.a"`)
- "./lib/travis_build_push.sh"
