# Project information
site_name:        'Gtools'
site_description: 'Faster Stata for Big Data'

nav:
    - Home: index.md
    - FAQs: faqs.md
    - Benchmarks: benchmarks.md
    - Compiling: compiling.md
    - Usage:
        - gtools:             usage/gtools.md
    - Data manipulation:      
        - gcollapse:          usage/gcollapse.md
        - greshape:           usage/greshape.md
        - gcontract:          usage/gcontract.md
        - gisid:              usage/gisid.md
        - glevelsof:          usage/glevelsof.md
        - gtop:               usage/gtoplevelsof.md
        - hashsort:           usage/hashsort.md
    - Statistics:             
        - gegen:              usage/gegen.md
        - gquantiles:         usage/gquantiles.md
        - gstats residualize: usage/gstats_hdfe.md
        - gstats winsor:      usage/gstats_winsor.md
        - gstats sum/tab:     usage/gstats_summarize.md
        - gstats transform:   usage/gstats_transform.md
        - gdistinct:          usage/gdistinct.md
        - gunique:            usage/gunique.md
        - gduplicates:        usage/gduplicates.md
    - Regression models:      
        - gregress:           usage/gregress.md
        - givregress:         usage/givregress.md
        - gglm:               usage/gglm.md

theme: readthedocs

# name: 'material'
#     primary: 'Teal'
#     accent: 'Teal'

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - helpers.js

markdown_extensions:
    - meta
    - toc
    - tables
    - fenced_code
    - admonition
    - codehilite:
        guess_lang: false

# use_pygments: True
# noclasses: True
# pygments_style: monokai

use_directory_urls: false

extra_css:
    - css/extra-rtd.css

# extra_css:
#     - css/extra-material.css
#     - css/extra-material-dark.css

# Repository
# repo_name: 'mcaceresb/stata-gtools'
# repo_url:  'https://github.com/mcaceresb/stata-gtools'
# edit_uri:  'blob/master/docs/'
# site_url:  'https://gtools.readthedocs.io/en/latest/'
