# Project information
site_name:        'Gtools'
site_description: 'Faster Stata for Big Data'

pages:
    - Home: index.md
    - FAQs: faqs.md
    - Benchmarks: benchmarks.md
    - Advanced:
        - Compiling: compiling.md
    - Usage:
        - gcollapse:     usage/gcollapse.md
        - gquantiles:    usage/gquantiles.md
        - greshape:      usage/greshape.md
        - gcontract:     usage/gcontract.md
        - gegen:         usage/gegen.md
        - gdistinct:     usage/gdistinct.md
        - gunique:       usage/gunique.md
        - gisid:         usage/gisid.md
        - gduplicates:   usage/gduplicates.md
        - glevelsof:     usage/glevelsof.md
        - gtop:          usage/gtoplevelsof.md
        - hashsort:      usage/hashsort.md
        - gtools:        usage/gtools.md
        - gstats:        
            - winsor:    usage/gstats_winsor.md
            - sum/tab:   usage/gstats_summarize.md

theme: readthedocs

# name: 'material'
#     primary: 'Teal'
#     accent: 'Teal'

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    - helpers.js

markdown_extensions:
    - meta
    - toc
    - tables
    - fenced_code
    - admonition
    - codehilite

# guess_lang: False
# use_pygments: True
# noclasses: True
# pygments_style: monokai

use_directory_urls: false

extra_css:
    - css/extra-rtd.css

# extra_css:
#     - css/extra-material.css
#     - css/extra-material-dark.css
